services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cnab-sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    restart: unless-stopped
    networks:
      - cnab-network

  api:
    build:
      context: .
      dockerfile: ./src/CnabImporter.Api/Dockerfile
    container_name: cnab-api
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CnabImporterDb;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;"
      DOTNET_ENVIRONMENT: Development
    ports:
      - "7195:5000"
    depends_on:
      - sqlserver
    restart: on-failure
    networks:
      - cnab-network
        
  sqlserver-test:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cnab-sqlserver-test
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1436:1433"
    restart: unless-stopped
    networks:
      - cnab-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: cnab-frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - cnab-network

networks:
  cnab-network:
    driver: bridge
